"""Risk-weighted coverage gate for core, adapter, and repo floors."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import cast


@dataclass(frozen=True, slots=True)
class CoverageBand:
    name: str
    threshold: float
    prefixes: tuple[str, ...]


CORE_BAND = CoverageBand(
    name="core_domain_application",
    threshold=90.0,
    prefixes=(
        "packages/contracts/src/contracts/models.py",
        "packages/shared-kernel/src/shared_kernel/assistant.py",
        "packages/shared-kernel/src/shared_kernel/credit_policy.py",
        "services/mlops/src/mlops_service/lifecycle.py",
    ),
)

ADAPTER_BAND = CoverageBand(
    name="adapters_integration_edges",
    threshold=70.0,
    prefixes=(
        "services/api-gateway/src/api_gateway/",
        "services/application/src/application_service/repositories.py",
        "services/feature/src/feature_service/repositories.py",
        "services/scoring/src/scoring_service/repositories.py",
        "services/decision/src/decision_service/repositories.py",
        "services/collab-assistant/src/collab_assistant/",
        "services/mlops/src/mlops_service/repositories.py",
        "services/observability-audit/src/observability_audit/repositories.py",
        "packages/shared-kernel/src/shared_kernel/database.py",
        "packages/shared-kernel/src/shared_kernel/messaging.py",
        "packages/shared-kernel/src/shared_kernel/outbox.py",
        "packages/shared-kernel/src/shared_kernel/outbox_relay.py",
    ),
)

REPO_THRESHOLD = 80.0


def _fail(message: str) -> int:
    print(f"[coverage-gate] {message}")
    return 1


def _load_coverage(path: Path) -> dict[str, object]:
    with path.open("r", encoding="utf-8") as handle:
        loaded = json.load(handle)
    if not isinstance(loaded, dict):
        raise ValueError("coverage payload root must be an object")
    return cast(dict[str, object], loaded)


def _matches(path: str, prefixes: tuple[str, ...]) -> bool:
    for prefix in prefixes:
        if path.startswith(prefix):
            return True
    return False


def _band_percent(files: dict[str, object], band: CoverageBand) -> tuple[float, int]:
    covered_lines = 0
    statements = 0
    matched_files = 0
    for file_path, file_data_obj in files.items():
        if not _matches(file_path, band.prefixes):
            continue
        if not isinstance(file_data_obj, dict):
            continue
        file_data = cast(dict[str, object], file_data_obj)
        summary_obj = file_data.get("summary")
        if not isinstance(summary_obj, dict):
            continue
        summary = cast(dict[str, object], summary_obj)
        covered_value = summary.get("covered_lines")
        statement_value = summary.get("num_statements")
        if not isinstance(covered_value, int):
            continue
        if not isinstance(statement_value, int):
            continue
        if statement_value == 0:
            continue
        covered_lines += covered_value
        statements += statement_value
        matched_files += 1
    if statements == 0:
        return 0.0, matched_files
    return (covered_lines / statements) * 100.0, matched_files


def main() -> int:
    parser = argparse.ArgumentParser(description="Enforce risk-weighted coverage gates")
    parser.add_argument(
        "--input",
        default="build/coverage.unit.json",
        help="Coverage JSON path generated by pytest-cov",
    )
    args = parser.parse_args()

    coverage_path = Path(args.input)
    if not coverage_path.exists():
        return _fail(f"coverage report not found: {coverage_path}")

    try:
        payload = _load_coverage(coverage_path)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return _fail(f"failed to load coverage report: {exc}")

    files_raw = payload.get("files")
    totals_raw = payload.get("totals")
    if not isinstance(files_raw, dict) or not isinstance(totals_raw, dict):
        return _fail("coverage report missing required 'files' or 'totals' sections")

    files = cast(dict[str, object], files_raw)
    totals = cast(dict[str, object], totals_raw)
    repo_percent_raw = totals.get("percent_covered")
    if not isinstance(repo_percent_raw, int | float):
        return _fail("coverage report missing totals.percent_covered")
    repo_percent = float(repo_percent_raw)

    failures: list[str] = []

    for band in (CORE_BAND, ADAPTER_BAND):
        percent, matched_files = _band_percent(files, band)
        print(
            "[coverage-gate] "
            f"{band.name}={percent:.2f}% threshold={band.threshold:.2f}% files={matched_files}"
        )
        if matched_files == 0:
            failures.append(f"{band.name}: no files matched coverage band prefixes")
            continue
        if percent < band.threshold:
            failures.append(f"{band.name}: {percent:.2f}% is below required {band.threshold:.2f}%")

    print(f"[coverage-gate] repo_total={repo_percent:.2f}% threshold={REPO_THRESHOLD:.2f}%")
    if repo_percent < REPO_THRESHOLD:
        failures.append(f"repo_total: {repo_percent:.2f}% is below required {REPO_THRESHOLD:.2f}%")

    if failures:
        for failure in failures:
            print(f"[coverage-gate] FAIL {failure}")
        return 1

    print("[coverage-gate] Coverage thresholds passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
